apiVersion: v1
kind: Namespace 
metadata:
  name: db
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: instancestorage
  namespace: db
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbvolumeclaim
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: instancestorage
---
apiVersion: v1
kind: Service
metadata:
  name: dbservice
  namespace: db
spec:
  ports:
    - port: 5984
      targetPort: 5984
  selector:
    app: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  namespace: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      name: couchdb
      labels:
        app: db
    spec:
      containers:
        - name: couchdb
          image: couchdb:latest
          volumeMounts:
            - name: dbvolume
              mountPath: /mnt/var
      volumes:
        - name: dbvolume
          persistentVolumeClaim:
            claimName: dbvolumeclaim
