apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-only-role
rules:
  - apiGroups: ['']
    resources: ['ResourceAll']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-role-binding
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: read-only-role
subjects:
  - kind: User
    name: test-user